### ISSUE TITLE
Keyword request "Press Key"

### ISSUE THREAD

**Issue by Nepitwin** [GDATASoftwareAG/robotframework-flaui#1]
As a tester, I want to have "Press Key" keyword.

we have already a keyword "Press keys" which takes a list of shortcuts as an argument but it is more practical to have one more keyword which just takes one key combination as a shortcut so that we avoid lists of one element.

Tasks to do

- [ ] Implement Press Key <XPATH> <KEY>
- [ ] Extend Keyboard.robot and ErrorHandling tests
- [ ] Update changelog
- [ ] Update documentation page
- [ ] Pylint is score 10/10
- [ ] Create pullrequest
- [ ] Merge to master

**Comment by Wasya** [comment]
Hi Nepitwin,
How did you even manage to send anything using Press Key. 
In my case, this KeyWord just always returns an error:

_FlaUiError: Keyboard keys combination t is not valid_

from just using the example the library author gave:
Press Keys  t'Example text' s'CTRL+A' s'CTRL+C'
how to use this **Press Keys** command at all?

**Comment by Nepitwin** [comment]
Hi @Wasya ,

an example usage is implemented here https://github.com/GDATASoftwareAG/robotframework-flaui/blob/master/atests/Keyboard.robot

The Press Keys keyword expects an xpath usage on which element this operation should be executed at the last statement.

For example a combobox  as variable for robotframework

${XPATH_COMBO_BOX_INPUT}    ${MAIN_WINDOW_SIMPLE_CONTROLS}/ComboBox[@AutomationId='EditableCombo']

For multiple key execution in common you create a list variable

@{KEYBOARD_INPUT_SELECT_CUT_TEXT}  s'CTRL+A'  s'CTRL+X'

Then you combine both in a keyword and it should execute the Keyboard operations

Press Keys  ${KEYBOARD_INPUT_SELECT_CUT_TEXT}  ${XPATH_COMBO_BOX_INPUT}

I think a better documentation for the Keyboard component would be an improvement.

Thanks for you response i hope the short descriptions helps.

**Comment by Wasya** [comment]
Hallo Nepitwin,

Thanks a lol Man! You very helped me. But you are 100% right - the documentation regarding of this concrete case should be improved. And I fully agree with your first request within this topic!

**Comment by Nepitwin** [comment]
For this use case i create a small new issue to create a smarte documentation about the keyboard keywords. Thanks for you reply.

https://github.com/GDATASoftwareAG/robotframework-flaui/issues/21
