### ISSUE TITLE
problem with simulating ctrl-click

### ISSUE THREAD

**Issue by alonk-me** [GDATASoftwareAG/robotframework-flaui#10]
I'm using the library to automate a windows application. I need to select several items in a data grid using ctrl-click. when I use the press keys keyword with 'CTRL+LBUTTON' it doesn't work but in the report it registers as a success . when I tried press keys "LBUTTON"  it again didn't click but registers as success.
I'm using windows 10, python 3.8 

is there another way to preform ctrl+click on an element?

**Comment by Nepitwin** [comment]
Hi alonk-me,

the Select Listview keywords can be also used to select items in a data grid by actual testing implementation they select multiple items in a DataGrid.

Examples are implemented in https://github.com/GDATASoftwareAG/robotframework-flaui/blob/master/atests/Listview.robot

I also include a DataGrid.robot robot testing file.

![image](https://user-images.githubusercontent.com/12249055/104635748-9f2ab900-56a2-11eb-8025-0b6212f60e6c.png)

Example code

```
*** Variables ***
${XPATH_LIST_VIEW}  ${MAIN_WINDOW_COMPLEX_CONTROLS}/Pane/Group[@Name='ListView']/DataGrid[@AutomationId='listView1']

*** Test Cases ***

Select Multiple Listview Row
    Select Listview Row By Name   ${XPATH_LIST_VIEW}  0  1
    Select Listview Row By Index  ${XPATH_LIST_VIEW}  1
    ${DATA}  Get Selected Listview Rows  ${XPATH_LIST_VIEW}
    Should Contain  ${DATA}  | 1 | 10 |
    Should Contain  ${DATA}  | 2 | 20 |
```

It could be an idea to create seperate keywords to clarify that DataGrids for a better name convention.

The press keys keyword will be investigate why this does not work and the test extended.

**Comment by Nepitwin** [comment]
Keyboard operation on data grid items can not be simulated by flaui. It's not possible to select items as simulation by ctrl-click.

Test example
```
*** Variables ***
${MAIN_WINDOW_COMPLEX_CONTROLS}                    ${MAIN_WINDOW}/Tab/TabItem[@Name='Complex Controls']
${XPATH_GRID_VIEW}  ${MAIN_WINDOW_COMPLEX_CONTROLS}/Pane/Group[@Name='Grid']/DataGrid[@AutomationId='dataGridView']
@{KEYBOARD_INPUT_SELECTION}    s'CTRL'  s'LBUTTON'

*** Test Cases ***

Select Multiple Grid Items By Keyboard
    Press Keys  ${KEYBOARD_INPUT_SELECTION}  ${XPATH_GRID_VIEW}/DataItem[1]
    ${DATA}  Get Selected Listview Rows  ${XPATH_GRID_VIEW}
    Should Contain  ${DATA}  | 2 | 20 |

InvalidOperationException: Der Vorgang ist aufgrund des aktuellen Zustands des Objekts ungültig.
   bei Interop.UIAutomationClient.IUIAutomationElement.SetFocus()
   bei FlaUI.Core.AutomationElements.AutomationElement.FocusNative()
```

**Comment by alonk-me** [comment]
Got it, thanks for the help and the reply
