### ISSUE TITLE
<Bug> "Take Screenshot" keyword only available for case which will run FAIL

### ISSUE THREAD

**Issue by JimRevolutionist** [GDATASoftwareAG/robotframework-flaui#105]
![image](https://github.com/GDATASoftwareAG/robotframework-flaui/assets/126214844/b6650b18-37b1-4b33-90ea-d65c5d69a7c0)

A long time no see you @Nepitwin 

In picture, you will find that "Take Screenshot" keyword will lose its capture jpg function in a PASS case

**Comment by Nepitwin** [comment]
- Take Screenshot keyword will now persist manually created screenshots
    - Automatic screenshots by failures will be still deleted
    - Screenshots contains now a timestamp
      - Required if multiple test executions are triggered by seperated names for example UIA2 and UIA3 testing
      - Screenshot has to be copied after rebot merge because paths are relative to test execution folder
         - Example usage 
         - call rebot --name ATests --outputdir result -x rebot_xunit.xml result/uia2/output.xml result/uia3/output.xml
         - call xcopy .\result\uia2\screenshots .\result\screenshots\
         - call xcopy .\result\uia3\screenshots .\result\screenshots\
