### ISSUE TITLE
Is it possible to use Locator found in Uia2 of FlaUInspector in this robot library

### ISSUE THREAD

**Issue by oz4899** [GDATASoftwareAG/robotframework-flaui#11]
my application undertest is discoverable only in Uia2 mode when i'm using FlauiInspector but when I tried to use that element in robot code with this library it say process ID not found. 

i guess i should config this library to run on Uia2 instead of Uia3 , could you help to guide on how i can config this ?

**Comment by Nepitwin** [comment]
By the current state only UIA3 will be used automatic by this wrapper.

I tested a small hotfix with UIA2.dll usage. There is no issue to implement the UIA2 usage. This will be supported in the next version.

- Include UIA2.dll from last FlaUI release
- Implement switch from library to switch to UIA2
- Default UIA3 will be used
- Update changelog

**Comment by Nepitwin** [comment]
Include changes https://github.com/GDATASoftwareAG/robotframework-flaui/commit/2ae7736fc9c8ae56dcbae2d0d5c398836d3f014e

**Comment by Nepitwin** [comment]
You can checkout develop/uia2_support branch.

- Build local robotframework-flaui with keen.bat  build
- Dist folder creates wheel file which can be used for local installation
