### ISSUE TITLE
Colons (and possibly other characters) in Test Cases Cause File Path Errors

### ISSUE THREAD

**Issue by GLMeece** [GDATASoftwareAG/robotframework-flaui#113]
# Summary

Most filesystems recognize the colon character as a path delimiter. For example, here are several reserved characters in Windows file systems, inclusive of the colon character. If a test case has a colon (or, likely any other illegal file/path character), the robotframework-FlaUI library does not escape the character, and thus tries to save screenshots using this as part of the filename.

## Example

Assuming we've installed and imported robotframework-flaui, a test case with this name:
```robotframework
Test Case 1234: Something to Test
    [Documentation]    Pretend we're testing something here...
    Log to Console    What's the state of the desktop?
    Take Screenshot
```
...will cause the library to _attempt_ to create a screenshot with a name like: `test_case_1234:_something_to_test.jpg`

## Issue

The screenshot cannot be successfully created because the colon is an illegal/reserved character.

**Comment by Nepitwin** [comment]
Invalid characters will be removed in future by testcase name and hostname.

**Comment by Nepitwin** [comment]
Fix merged to master next Version will fix this issue.
