### ISSUE TITLE
[Bug] Combobox will not restore into Collapsed state after calling 4 related keywords.

### ISSUE THREAD

**Issue by JimRevolutionist** [GDATASoftwareAG/robotframework-flaui#117]
Dear @Nepitwin  that's a long time no seeing you, hope you're enjoying your life. 

Well, let's back to the topic. When I tested in these cases, I found it will expand combobox element but not execute restore action to collapse. So I think it's a bug.

Get All Names From Combobox
Get All Texts From Combobox
Get Combobox Items Count
Combobox Should Contain

Cases: 
[1] call any one keyword.
[2] call multiple diff keywords together.

Actual Result:
[1] combobox element will be expanded only once in these cases.
[2] result will not affect below calling Select Combobox Item By Index, that's good.

But if you want to click other button, when the combobox element is expanded, the button will be not enabled and cannot be clicked.

**Comment by JimRevolutionist** [comment]
fixes: add control.Collapse() before return in these 4 keywords

![image](https://github.com/GDATASoftwareAG/robotframework-flaui/assets/126214844/183f69d6-22bd-452a-b3cd-b4387f4bbc5f)

![image](https://github.com/GDATASoftwareAG/robotframework-flaui/assets/126214844/fbc90c4f-eb73-44e8-b6f9-a60f1ad57346)

**Comment by Nepitwin** [comment]
@JimRevolutionist 

This will be fixxed in next release. Yes all interaction elements like a listbox combobox etc. should automatic close the visualization to avoid such a issue.

**Comment by JimRevolutionist** [comment]
I have created pr (/pull/120) for this bug issue, pls review. @Nepitwin
