### ISSUE TITLE
Take Screenshot On Failure doesn't work while using Run Keyword And Ignore Error

### ISSUE THREAD

**Issue by vonMort** [GDATASoftwareAG/robotframework-flaui#122]
**Issue Description:**
The functionality to capture screenshots on failure doesn't seem to work as expected when using the Run Keyword And Ignore Error keyword.

**Detailed Explanation:**
In the context of the robotframework-flaui library, there appears to be an issue with capturing screenshots when using the Run Keyword And Ignore Error keyword. This behavior seems to stem from how the library handles screenshots during test execution.

From my understanding, the robotframework-flaui library has a feature where it captures screenshots for all tests, storing them temporarily. However, these screenshots are only retained if the test result is "failed." In cases where the test result is "passed," the library deletes the captured screenshots.

The specific problem arises when using the Run Keyword And Ignore Error keyword. This keyword internally reports a failure, but then simulates a "passed" status. As a result, the library treats this scenario as a successful test, leading to the deletion of any captured screenshots, even though there was an issue that was ignored.

**Expected Behavior:**
Ideally, when using the Run Keyword And Ignore Error keyword, the library should still retain captured screenshots even if the keyword itself reports a failure but the overall test status is considered "passed."

**Additional Information:**

-     Library: robotframework-flaui
-     Keyword in question: Run Keyword And Ignore Error
-     This behavior was confirmed in conversation with Nepitwin.

**Steps to Reproduce:**

1.     Set up a test case using the Run Keyword And Ignore Error keyword.
2.     Intentionally introduce an error within the keyword's scope.
3.     Execute the test.
4.     Check if screenshots are captured and retained, despite the keyword reporting a failure that is ignored.

**Environment:**

-     Robot Framework version: [6.0.1]
-     Operating System: [Windows 11, Windows 10 1808, Windows Server 2022]

**Note:**
I understand that the library behavior might be by design, but given the usage of the Run Keyword And Ignore Error keyword, it might be beneficial to reevaluate how screenshots are managed in such scenarios.

**Comment by Nepitwin** [comment]
- Whitelisting and blacklisting keywords implemented for screenshot library
    - Keywords can be whitelisted to persist if failed for example
      - BuiltIn.Run Keyword And Ignore Error should track always a screenshot
    - Keywords can be blacklisted to ignore by screenshot module
      - BuiltIn.Wait Until Keyword Succeeds
    - Blacklist is prioritize before Whitelist 
  - New Keywords Clear Whitelist and Clear Blacklist
