### ISSUE TITLE
Compatibility with Robot Framework 3.2.2 

### ISSUE THREAD

**Issue by nizwiz** [GDATASoftwareAG/robotframework-flaui#13]
Latest stable release of RF is [3.2.2](https://github.com/robotframework/robotframework/releases/tag/v3.2.2),
but requirements.txt states "robotframework>=3.0.4,<=3.2.1".
Is there a specific reason for the constraint, or can requirements.txt be updated to include 3.2.2?

**Comment by Nepitwin** [comment]
The question was already asked in the Issue https://github.com/GDATASoftwareAG/robotframework-flaui/issues/6.

The plan was also to update the versioning of the robot framework to 3.2.2, as this does not cause any problems with the library.

I think I will just create a hotfix release for the Requirments.txt and update it.
