### ISSUE TITLE
Is robotframework-flaui supported on windows 11 ?

### ISSUE THREAD

**Issue by naagf5** [GDATASoftwareAG/robotframework-flaui#130]
Is robotframework-flaui supported on windows 11 ?

**Comment by Nepitwin** [comment]
@naagf5 

Yes Windows 11 is supported with Robotframework-Flaui.

**Comment by naagf5** [comment]
Installed and verified on below combination. Working Perfectly.
WINDOWS : WINDOWS 11 with latest patch sep 2023 (released 12th sep)
robotframework==3.0.4
robotframework-flaui==1.6.4

Hence closing the issue.
