### ISSUE TITLE
Relative xpath is taking very long time when compared to Absolute xpath 

### ISSUE THREAD

**Issue by vamsivarma94** [GDATASoftwareAG/robotframework-flaui#131]
Usually in web automation there won't be much difference in execution time between Absolute xpath and Relative xpath but here in our library Relative Xpath (//Edit[@Name='Notepad']) is taking very long time than expected.

New Keyword Request:
Wait Until Entire Window loads (This will help us in reducing all sync issues. We have few methods related to this one in FLAUI.CORE application.cs. )

**Comment by Nepitwin** [comment]
@vamsivarma94 

Ah i see in Application.cs

WaitWhileBusy
WaitWhileMainHandleIsMissing

Asweel i woud give a opportunity to get an handle from a window if needed from ProcessId

https://github.com/FlaUI/FlaUI/blob/master/src/FlaUI.Core/Application.cs

Do you mean this kind of methods from Application.cs? Because all other methods would not help to identify probably your issue.

**Comment by vamsivarma94** [comment]
Yes @Nepitwin the above mentioned methods WaitWhileBusy
WaitWhileMainHandleIsMissing would definitely help in reducing sync issues

**Comment by vamsivarma94** [comment]
@Nepitwin can we do something on relative xpath which is taking more time to find an element to perform activity. Usually in white framework they are using only name, automation I'd,name and helptext but it will identify and perform activity fastly.

**Comment by vamsivarma94** [comment]
https://github.com/amruthvvkp/flaui-uiautomation-wrapper/blob/master/flaui/wrappers/core/applicaiton.py 

I think if we go through the above link they already implemented those keywords from flaui dlls. What I strongly believe is they are plenty of good and useful methods are available from flaui dlls I think we can implement them in our library to make ours as a robost framework.

Thanks a lot @Nepitwin for all your contribution and support.
