### ISSUE TITLE
UIA2 exception during intializing 

### ISSUE THREAD

**Issue by FMRZDK** [GDATASoftwareAG/robotframework-flaui#138]
@Nepitwin  After updating the FlaUI library version from 2.0.13 to 2.0.14 exceptions appearing when initializing the FlaUI library during test execution via Robot Framework.
[Exception FlaUI rollout.txt](https://github.com/GDATASoftwareAG/robotframework-flaui/files/13459256/Exception.FlaUI.rollout.txt)
exception is related to UIA2. Only our Win7 machines are affected
Win10 and 11 is working as expected.

**Comment by Nepitwin** [comment]
UIA2 object initialization failed by windows 7 host machines.

Bugfix will be affected to 2.0.15 version and 2.1.1.
