### ISSUE TITLE
Issue with Key Up Key Down events in test application

### ISSUE THREAD

**Issue by GeoGegl** [GDATASoftwareAG/robotframework-flaui#152]
**Summary**
In the test application "WpfApplication.exe" in the "Keyboard Controls" tab, 
the Keyboard Down Events label does not work for some keys. E.g. Arrow Keys
(The Keyboard Up Events work)

**Steps to reproduce**
* Go to the "Keyboard Controls" tab in the test application "WpfApplication.exe"
* Select input field
* Type keys: A, B, C
* observe Keyboard Down Events label and Keyboard Up Events label
* Type the arrow keys on the keyboad: Left, Right, Up, Down
* observe Keyboard Down Events label and Keyboard Up Events label

The Keyboard Up Events displays everything correctly for me.
Did anyone else experience this behavior?

I wrote a test case to check the behavior.

I used the latest release 3.0.0

**Comment by Nepitwin** [comment]
@GeoGegl 

Thanks for you PR i think this shows the issue here in detail. Yes Issue 67 was about unity that keyboard events was not triggered.

We only send all command to FlaUI C# Keyboard implementation. I will recheck if any bug on robotframework wrapper side is made.

From issue 67 the last information was that the Keyboard implemention from FlaUI has to be adjusted probably a fix is done because i not recheck the library changes.

- [ ] Recheck Robotframework-FlaUI if any wrong data is send to FlaUI Keyboard
- [ ] Recheck FlaUI if a bugfix exists by Keyboard usage

**Comment by noubar** [comment]
i have retested WPFtestapp manually with the keyboard it seems the app itself has some issues.
The down button is not showing the arrows even when i am typing with keyboard manually.
I suggest also that we look for the source code of the test app

**Comment by noubar** [comment]
Reproductions steps are.
Open WpfApplication.exe
Go to keyboard Controls tab
Press and release 'a': everythin works fine
Press and release 'down arrow': still works fine
Press and release 'up arrow': the keyboard up event showing fine but keyboard down is not showing.

**Comment by Nepitwin** [comment]
After verification and mentioned noubars text. OnKeyDown event is only triggered once by key operations.

**Comment by Nepitwin** [comment]
@GeoGegl  Can you pls take changes from branch bugfix/#152 

I adjusted the wpf test application to handle events correctly. But i see in your test case that the expected input by release_only is wrong by your test case pls adjust them.

**Comment by GeoGegl** [comment]
Thanks a lot! I'll work on it ASAP

**Comment by GeoGegl** [comment]
I updated to ignore case in the key up / down test case.
And I also did a change on the WPF application.
I took over your PreviewKeyDown / Up entries but changed the behvior of
displaying the events in the WPF application.
As I'm new to github I'm not sure: Can you see my changes in the pull request?

What do you think about the changed event displaying?
My intention was to display all key down events until the keys are released.
And to display all key up events when they occur until no key is held down anymore - 
only then a new list of key up events is displayed.
-> My test case does not cover all of that - but I guess it should be added in future

**Comment by noubar** [comment]
I think you have done it very well
Make the small changes @Nepitwin has asked in PR review.
Then we can merge into the main

My concern is though this press_only or up_only feature currently works only with keys starting with s'SOMEKEY' but not with text t'SOMETEXT'. And there is no code implemented to prevent it. As example error message saying you cannot use press_only or up_only feature with text.

**Comment by GeoGegl** [comment]
Thanks for your input. I added the check and error message for text pattern and updated the changelog.
