### ISSUE TITLE
Stable Flauinspect

### ISSUE THREAD

**Issue by noubar** [GDATASoftwareAG/robotframework-flaui#156]
After having to much trouble with FlaUInspect official version (it breaks all the time) and seeing that the repo is not being developed and improvement PRs are not let to merge. I have decided to fork my own version make things stable and let improvements and new ideas in.
https://github.com/noubar/FlaUInspectStable
So within this repo i am suggesting to update the readme and name additionally my own stable version beside the official link.

**Comment by Nepitwin** [comment]
You can extend the readme as additional GUI Inspector Tool.

**Comment by Nepitwin** [comment]
Readme is upgraded thanks for you work @noubar
