### ISSUE TITLE
Focus element does not have error handling

### ISSUE THREAD

**Issue by noubar** [GDATASoftwareAG/robotframework-flaui#158]
The following two lines of focus element do not have error hanling.

- https://github.com/GDATASoftwareAG/robotframework-flaui/blob/main/src/FlaUILibrary/flaui/module/element.py#L90
- https://github.com/GDATASoftwareAG/robotframework-flaui/blob/main/src/FlaUILibrary/flaui/module/element.py#L96

I am suggesting to build error handling like all other element module funtions.
Currently the following error text is thrown out:

InvalidOperationException: Target element cannot receive focus.
   at System.Windows.Automation.AutomationElement.SetFocus()
   at FlaUI.Core.AutomationElements.AutomationElement.FocusNative()

**Comment by Nepitwin** [comment]
@noubar  yeah you are right. We should extend this keywords as functions and maintain this with error handling.
