### ISSUE TITLE
Keyword "Find All Elements" fails (here: Property "ClassName" is "Not Supported")

### ISSUE THREAD

**Issue by JanR-W** [GDATASoftwareAG/robotframework-flaui#160]
Hello,
in our AUT the UI elements have the property "ClassName" show up as "Not Supported":
![image](https://github.com/GDATASoftwareAG/robotframework-flaui/assets/93187857/ca7bfc84-d569-4418-9018-1d0bbf1ee772)

Apparently this leads to an error when using the keyword `Find All Elements` (I'm using the rfdebugger library to debug my keywords interactively inside of my console, but the same error occurs if I use the keyword inside of my test scripts):
>`> ${edit}=  Set Variable  /Window/Pane[3]/Window/Pane/Pane/Window[2]/Edit[@Name='user_s']`
`# ${edit} = "/Window/Pane[3]/Window/Pane/Pane/Window[2]/Edit[@Name='user_s']`
`> Find All Elements  ${edit}`
`! keyword: Find All Elements  ${edit}`
`! handler execution failed: PropertyNotSupportedException: The requested property 'ClassName [#30012]' is not supported
   bei FlaUI.Core.FrameworkAutomationElementBase.GetPropertyValue[T](PropertyId property)`

Would it be possible to extend `Find All Elements` with an (optional) argument so that it only tries to read the property of the found elements I actually need and know is supported in my AUT? If not specified it could keep its old behaviour to return all three properties (making it hopefully a non-breaking change to the keyword).

To make it hopefully a bit more clear: I'm thinking of something like this:
Keyword | Arg1 | Arg2 | Arg3
--- | --- | --- | ---
Find All Elements | \<identifier\> | msg=None | \<property: Either XPATH or AUTOMATION_ID or CLASS_NAME or `None`, if not specified\>

**Comment by Nepitwin** [comment]
@JanR-W 
Thank you for reporting the issue.

This was not considered within the method that properties are not available.

def _find_all_elements(self, xpath: str):
        values = []
        elements = self._get_all_elements_by_xpath(xpath)
        for element in elements:
            values.append(AutomationElement(
                element.AutomationId,
                element.Name,
                element.ClassName,
                FlaUIDebug.GetXPathToElement(element)
            ))

        return values

Since these are accessed in the Find_All_Elements method and should be saved as a list, there is probably an exception within the execution on this element.

This is a bug that we will fix.

We could solve this with an argument that can be selected and also that there is simply an empty string.

**Comment by JanR-W** [comment]
That was a very quick fix, thank you so much!
