### ISSUE TITLE
Screenshot on Failure generates multiple images

### ISSUE THREAD

**Issue by rogerjagare** [GDATASoftwareAG/robotframework-flaui#169]
When you have multiple levels of custom keywords, it seems like FlaUI generates multiple images.

| Level 1 | Level 2 | Level 3 |
|--------|--------|--------|
| Main Keyword | Sub Keyword 1 |  FlaUI Keyword 1  Status: PASS |
|                         | Sub Keyword 2 |  FlaUI Keyword 2  Status: Fail |

The scenario above will generate 3 images.
It looks like one image is created for failing 
**FlaUI Keyword 2**, one for **Sub Keyword 2** and one for **Main Keyword**       

This testfile will show the issue:
[test_flaui_error_screenshot.txt](https://github.com/GDATASoftwareAG/robotframework-flaui/files/14615037/test_flaui_error_screenshot.txt)

**Comment by noubar** [comment]
Related to #148 Could be analyzed and fixed together

**Comment by Nepitwin** [comment]
@rogerjagare 

Thanks for you issue. Yes currently if a keyword internally fails scrennshots will be created from all called keywords.

This creates a lot of screenshot data and correct behavior should be that screenshots should only be created on first failed keywords.

Keywords which are looping should asweel not cause an internal screeenshot.

Screenshoot module has to be adjusted here.
