### ISSUE TITLE
Add a set of keywords for tree and tree items

### ISSUE THREAD

**Issue by jridderbusch** [GDATASoftwareAG/robotframework-flaui#17]
Add the keywords:

- Select TreeItem By Name
- Select TreeItem By Index
- TreeItem Should be Selceted &nbsp;&nbsp;&nbsp;&nbsp; Name or Index

**Comment by Nepitwin** [comment]
Tasks to do

- [ ] Select TreeItem By Name <XPATH> <NAME>
- [ ] Select TreeItemBy Inde <XPATH> <INDEX>
- [ ] TreeItem Should Be Selected Name <XPATH> <NAME>
- [ ] TreeItem Should Be Selected Index <XPATH> <INDEX>
- [ ] Update changelog
- [ ] Pylint is score 10/10
- [ ] Pullrequest open
- [ ] Merge to master

**Comment by Nepitwin** [comment]
> Add the keywords:
> 
> * Select TreeItem By Name
> * Select TreeItem By Index
> * TreeITem Should be Selceted     Name or Index
> 
> Also check if Select ListboxItem By Name is possible.

Tasks to do

- [ ] Implement Select Tree Item By Name <XPATH> <NAME>
- [ ] Implement Select Tree Item By Index <XPATH> <INDEX>
- [ ] Implement Tree Item Should Be Selected Name <XPATH> <NAME>
- [ ] Implement Tree Item Should Be Selected Index <XPATH> <INDEX>
- [ ] Write tests Tree.robot and extend ErrorHandling tests for Tree
- [ ] Update changelog
- [ ] Pylint is score 10/10
- [ ] Pullrequest
- [ ] Merge to master

**Comment by fengnex** [comment]
Exciting news!
I wonder when I can use the above keywords to test tree controls, and I am looking forward to using them!
Could anyone please give some tips about the overall plan?

**Comment by fengnex** [comment]
The is a tab named "Complex Controls" that contains a tree control with items called  "Lvl**" on the UI of "FlaUI WPF Test APP". I really want to know how to test it with the robotframework-flaui library.

Any tips on how to write robot scripts to test tree controls, including developing customerized python programs, would be greatly appreciated!

**Comment by fengnex** [comment]
1. ClickTreeItem By Name
2. Click TreeItem By Index
3. Double ClickTreeItem By Name
4. Double Click TreeItem By Index

These four keywords are recommended to be supported too.

**Comment by fengnex** [comment]
Hello gentlemen,

When can we use the set of keywords for tree items? Would anyone be so kind as to give some relevant time points?

**Comment by noubar** [comment]
Hello gentlemen,
I would say best case scenario next week.

**Comment by noubar** [comment]
> 1. ClickTreeItem By Name
> 2. Click TreeItem By Index
> 3. Double ClickTreeItem By Name
> 4. Double Click TreeItem By Index
> 
> These four keywords are recommended to be supported too.

What do you mean really with double click.
What is the difference between double and single click on an item. Do you mean select or expand an item?

**Comment by fengnex** [comment]
You know asynchronize call would often be used to retrieve data from remote services when there there are many items in a tree, which is usually triggered by a double click action. That is it.

Maybe the keyword "Double Click" is already ok for it.

**Comment by fengnex** [comment]
Good news!
It would be great if we could use it next week!

**Comment by Nepitwin** [comment]
@fengnex 

The keywords are planned by a tree syntax usage for each keyword:
  * Number index based (I<NUMBER>) from root for example: Select Tree Node I0->I2 
  * Name based (N<NAME_FROME_TREE_NODE> from root for example Select Tree Node  NName_A->NName_B
  * Can be also used in mixed content for example: Select Tree Node  NName_A->I2->NName_B

Mixed mode can be used to select the correct nodes. If several nodes have the same name.

**Comment by fengnex** [comment]
Thank you!@Nepitwin
Look forward to being able to use the tree relevant keywords this week!

**Comment by fengnex** [comment]
Is there any progress recently and can  we use the new keywords this week?

**Comment by fengnex** [comment]
@noubar Great!
I will test it this week!

**Comment by fengnex** [comment]
There is no effective way for me now to get the corrext xpath for the tree view in the tested WPF application.
@noubar Could you please provide some tips or tools for that? Thank you first.

**Comment by noubar** [comment]
> There is no effective way for me now to get the corrext xpath for the tree view in the tested WPF application.
> @noubar Could you please provide some tips or tools for that? Thank you first.
> 
> I used "Accessibility Insights for Windows" to check my app and the libraries' WpfApplication, and I found that "Accessibility Insights for Windows" can accurately locate WpfApplication's tree control, but on my app, it found nothing.
> 
> Maybe I need to try another test tools in order to test my wpf app. 

Read please the readme of this repository
There is a list of effective tools.
I personaly use flauiinspect

**Comment by fengnex** [comment]
![image](https://user-images.githubusercontent.com/26297547/113466270-133c5800-946d-11eb-93ba-68d15ad5087e.png)
The tree control I need to test is not the native one provided in WPF, whose code looks like that in the above image.

Is it possible to test it with robotframework-flaui?

**Comment by fengnex** [comment]
It seems like a customerized tree control and whether there is any way to test it with robotframework-flaui?

**Comment by Nepitwin** [comment]
What kind of tree view is it? Which gui framework is in usage here?

The requirements are the same as in the FlaUI core component in C#. If these are testable and accessible via C#, there are possibilities to make them available via the robot framework as well.

However, the requirements of the Windows specific test automation for GUI elements must apply. Special UI elements or self-written implementations must have the respective interface implemented for Windows automation (UIA2 or UIA3).

https://docs.microsoft.com/de-de/dotnet/framework/ui-automation/ui-automation-overview

**Comment by fengnex** [comment]
It's a WPF application developed with C# based on .Net, but the tree control is customerized.
I currently don't know the root cause that makes it unaccessible to robotframework-flaui and I will do some investigation.
