### ISSUE TITLE
Robot API Listeners execute FlauiLibrary-specific handling for all keywords

### ISSUE THREAD

**Issue by FrSchmied** [GDATASoftwareAG/robotframework-flaui#179]
FlaUILibrary handles screenshots on failure by using the Robot Framework (refered to as _RFW_ below) API Listener interface: [RFW Listener interface documentation](https://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#listener-interface).

However, the way it's currently set up, the _end_keyword_ listener defined in [init.py](https://github.com/GDATASoftwareAG/robotframework-flaui/blob/main/src/FlaUILibrary/__init__.py) (row 173) will execute its logic regardless of what keyword triggered the listener event. I think it should only trigger from FlaUILibrary keywords.

This results in the following outcomes I think are odd:

- All keywords takes a screenshot on failure. 
     - Even from the RFW BuiltIn library (BuiltIn.Fail for example).
- If the failing keyword is called from another keyword (that is called from another keyword etc.), all keywords in that chain will trigger the _end keyword_ listener event, and since RFW considers all those keywords as failed, screenshots will be taken for each. 
(see #169 which is related to this)

**Suggestion**
The listeners have a dictionary parameter _attrs_ that contain a key called _libname_ which holds the name of the library the keyword is part of. Could it perhaps be used to return from the listener early if the keyword trigger is not part of FlaUILibrary?

**Comment by noubar** [comment]
I would say that the flaui itself makes an screenshot for builtin libraries or others if they fail is not dramatic it is even useful. Our main problem with screenshot is the "nested keywords". Currently there is no mechanism to diffenciate between nested or not nested keyword.

Let say we have three level of nested Flaui keyword. The issue will remain existing.

**Comment by FrSchmied** [comment]
SeleniumLibrary also has screenshot on failure functionality. If a test runs both FlaUILibrary and SeleniumLibrary, then FlaUI will take screenshots on failing Selenium keywords. That is on top of the Selenium screenshot. SeleniumLibrary on the other hand, only takes screenshots when its own keywords have failed.

**Comment by Nepitwin** [comment]
Redesign from Screenshoot module is made which will be create only screenshots on FlaUILibrary kewords.
