### ISSUE TITLE
Not taking screenshots on failure when setting custom name

### ISSUE THREAD

**Issue by Abuturku** [GDATASoftwareAG/robotframework-flaui#206]
According to https://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#toc-entry-314 you can set a custom name for libraries when importing them, for example: 

``Library    FlaUILibrary    screenshot_on_failure=True    screenshot_dir=${FAILURE_IMG_DIR}    AS    FLA``

Now I think the issue is caused by this check in _end_keyword in src/FlaUILibrary/\_\_init.py\_\_ in line 165

``attrs['libname'] == "FlaUILibrary"``

It seems as if Robot Framework is overwriting the libname attribute with the custom name. When debugging I added a line to print out the attrs variable and it showed: 

``'libname': 'FLA'``

**Comment by Nepitwin** [comment]
Intresting behavior i will look into this next week how to fix custom libray names. Expected behavior should be that of cours libname comparsion should FLA not FlaUILibrary

**Comment by Nepitwin** [comment]
Alias usage can not be obtained directly from python code. So i will create a new parameter alias which can be set

For example

Library    FlaUILibrary    screenshot_on_failure=True    screenshot_dir=${FAILURE_IMG_DIR}  alias=FLA    AS    FLA

afterwards i will use this alias. By default it will be FlaUILibrary

**Comment by noubar** [comment]
I was using this feature to be honest even before this last merge and it was functioning well
```
*** Settings ***
Library  FlaUILibrary  AS  fla

*** Keyword **

fla.click  <xpath>

```

@Abuturku what was the robot version you were testing with
