### ISSUE TITLE
Launch app with custom protocol and passing parameters

### ISSUE THREAD

**Issue by lhlhai** [GDATASoftwareAG/robotframework-flaui#212]
As described in the title, I have to launch app with custom protocol and passing some parameters in the uri.
Example command I used on Powershell:
`Start-Process "my-custom-protocol:?username=myusername&password=mypassword"`

```xml
<Application>
...
   <Extensions>
     <uap:Extension Category="windows.protocol">
        <uap:Protocol Name="my-custom-protocol"/>
     </uap:Extension>
   </Extensions>
  
...
</Application>
```

Thank you

**Comment by noubar** [comment]
@lhlhai 

you could use 

```
*** Settings ***
Library    Process
*** Test Cases ***
test
    Start Process    Powershell  Start-Process  "my-custom-protocol:?username=myusername&password=mypassword"

```

**Comment by lhlhai** [comment]
> :?username=myusername&password=mypassword

Thanks for your suggestion, however I was able to start without parameters, when I passed the params got an error: 
`! FAIL: Keyword argument '"my-protocol:?username' is not supported by this keyword.`

**Comment by lhlhai** [comment]
> @lhlhai
> 
> you could use
> 
> ```
> *** Settings ***
> Library    Process
> *** Test Cases ***
> test
>     Start Process    Powershell  Start-Process  "my-custom-protocol:?username=myusername&password=mypassword"
> ```

Thanks for your support, it's work.
