### ISSUE TITLE
removing redundant alias argument

### ISSUE THREAD

**Issue by noubar** [GDATASoftwareAG/robotframework-flaui#216]
No other robot library requires an extra alias to be initiated so the following example of library importing works
```
Library  libraryname AS shortname 
```

So i am suggesting to remove the alias implemented as a workaround for #206.
And solve the problem in a better way
Look selenium library as an example it also works without any workarounds

**Comment by Nepitwin** [comment]
This will be removed in future by internal usage without listener api from robotframework. Robotframework Flaui handles all errors with an own exception. so if a FlaUIException will be raised screenshot module will be called afterwards and will be include with an flag screenshot create to identify if an screenshot was made.
