### ISSUE TITLE
Keyword Mouse Drag and Drop

### ISSUE THREAD

**Issue by mr-rampage** [GDATASoftwareAG/robotframework-flaui#25]
Would it be possible to get a Mouse Drag/Drop keywords? I'm willing to contribute, but I'll need lots of guidance as I haven't learned Python or how RobotFramework works under the hood.

**Comment by Nepitwin** [comment]
Thanks for the response. I think there are two improvments. How to start to implement it by a wiki page.

And of course thie keyword would be a nice new enhancment from robotframework-flaui.

**Comment by noubar** [comment]
@Nepitwin and @mr-rampage what do you think is a new single keyword for drag and drop is enough to close this ticket? 
Which i already implemented

**Comment by Nepitwin** [comment]
@noubar 

Pls create a pull request for it ;) Sure it's enough because this is the task here ;) Inspect and adapt what is needed
