### ISSUE TITLE
ComboBox Support for index 0

### ISSUE THREAD

**Issue by Mavnus04** [GDATASoftwareAG/robotframework-flaui#55]
I am facing a strange issue with a 'ComboBox' on my GUI. 
If I try [Select Combobox Item By Index](https://gdatasoftwareag.github.io/robotframework-flaui/keywords/1.6.6.html#Select%20Combobox%20Item%20By%20Index) with index 0, I get this error:
`TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'` 
If I start at index 1 and go to the end, no problem. 

    Element Should Exist  ${xPath}
    ${count} =  Get ComboBox Items Count  ${xPath}
    Log  ${count}
    FOR  ${i}  IN RANGE  0  ${count}
        Select ComboBox Item By Index  ${xPath}  ${i}
        ${data} =  Get Selected Items From ComboBox  ${xPath}
    END

Also, is there a faster/more efficient way to get all the items from a combobox? For my GUI, I am seeing about 600ms per item in the list. The first couple of items take about 1 to 2 seconds each

**Comment by Nepitwin** [comment]
@Mavnus04 

Index 0 must be work i already adjust some code changes for next release.

If you want you can install this version locally and test if this index error still exists.

[Master_wheels.zip](https://github.com/GDATASoftwareAG/robotframework-flaui/files/8003089/Master_wheels.zip)

I will extend the atest for this case to see if this issue exists.

Also an new additional keyword would be nice

${data}  Get All Selected Names From Combobox
${data}  Get All Names From Combobox

**Comment by Nepitwin** [comment]
### Added 

- New Keywords implemented for listbox and combobox
  - Get All Names From Listbox and Get All Names From Combobox returns both a list from all values by names
  - For a list comparison pls use Collections library from robotframework

```
${data}  Get All Names From Listbox  <XPATH>
${data}  Get All Names From Combobox  <XPATH>
```

**Comment by Nepitwin** [comment]
Bugfix for Index 0 is already fix by converter fixxes from previous pull requests.
New keywords are implemented to get text values from items by listbox or combobox.

This feature changes will be released in version 1.7 from robotframework-flaui

**Comment by Mavnus04** [comment]
@Nepitwin Got version 1.7.1 and the new combobox keywords are working great.  Select by index with 0 is working as well now. Thank you!

However, when I use [Select Combobox Item By Index](https://gdatasoftwareag.github.io/robotframework-flaui/keywords/1.7.1.html#Select%20Combobox%20Item%20By%20Index), the drop down itself continues to stay down.  I have to add an additional `Click  ${CB_XPath}` to collapse the drop down.  When a user mouse clicks the selected item, the drop down collapses.  Is this something due to my GUI or the library FlaUI ?

**Comment by Nepitwin** [comment]
@Mavnus04 

That is great. Oh what i can from a combobox it contains a collapse and expand usage. This behaviour is correct than that the combobox expands by a ui interaction.

I think for an better ui handling i would recommend to implement the missing keywords to colapse and expans such an element. So than you do not have to click to the current element to hide it.

I will create another additional issue for this missing keywords.
