### ISSUE TITLE
Python 3.9 Support

### ISSUE THREAD

**Issue by Nepitwin** [GDATASoftwareAG/robotframework-flaui#6]
By current state Python 3.9 is not supported because Pythonnet does not support 3.9 by current state.

- [x] Wait until Pythonet release is upgraded to new version --> https://github.com/pythonnet/pythonnet/pull/1264
- [x] Extend matrix job for python 3.9 testing by appveyor.yml --> https://ci.appveyor.com/project/GDATACyberDefenseAG/robotframework-flaui/builds/37106381
- [x] Update documentation
- [x] Update robotframework dependency to latest version
- [ ] Merge to master
- [x] Update CHANGELOG

**Comment by Nepitwin** [comment]
Changes contains to 1.3.5 release.

https://github.com/GDATASoftwareAG/robotframework-flaui/commit/72f02f6f234d58407e594f99c0dd0e92e028257c

**Comment by mustafatalha** [comment]
Hi @Nepitwin,

Will robotframework dependency be updated as <=3.2.2 after supporting Python 3.9?

**Comment by Nepitwin** [comment]
Hi @mustafatalha 

of course it can be upgrade to the newest release from robotframework. I already include this depenendency in this request.

https://github.com/GDATASoftwareAG/robotframework-flaui/commit/ca3a80f83499ec256b2aeda01da14cc0074c51ab

**Comment by mustafatalha** [comment]
@Nepitwin Thank you for fast reply and update. I am looking forward to next pip release then. Is there anything I can help with this?

**Comment by Nepitwin** [comment]
@mustafatalha 

Thanks for the offer. This version will be released if pythonnet is updated for 3.9.

Only have to wait :)
