### ISSUE TITLE
Some button presses are very slow

### ISSUE THREAD

**Issue by Mavnus04** [GDATASoftwareAG/robotframework-flaui#61]
For certain buttons, the amount of time to press them is about 5 or more seconds.  But other buttons are press in under half a second. 
I made this little keyword to check, then click

    Click on GUI element
        [Arguments]  ${element}
        Log Many  ${element}
        Wait Until Element Is Visible  ${element}[xPath]
        Click  ${element}[xPath]

This xPath took half a second for the wait, then under a half to press:  
"/Window[@Name='DevTool']/Tab//Button[@Name='Connect']"

Where as this xPath took over 5 seconds to wait, then another 5 seconds to press
"/Window[@Name='DevTool']/Tab/Pane//Group[@Name='Game Control']/Button[@Name='Disable']"

Any idea why this might be happening?  These xPaths are in the same window, just under different tabs. 
I have something like this:

    Attach to application
    Switch to tab 1
    Click on GUI element   connect button       # 1 second
    Switch to tab 2
    Click on GUI element   disable button        # 10 seconds 
    Switch to tab 1
    Click on GUI element  disconnect button   # 1 second

**Comment by Mavnus04** [comment]
Solved my issue. 

I guess my search xPath was causing the slowness.  Direct path is much faster.  Note the extra slash before group.
Prev using: `"/Window[@Name='DevTool']/Tab/Pane//Group[@Name='Game Control']/Button[@Name='Disable']"`
Now using: `"/Window[@Name='DevTool']/Tab/Pane/Group[@Name='Game Control']/Button[@Name='Disable']"`

I was using the search xPath cause I was being lazy in setting my variables. Didn't realize the search would add that much extra time into finding and pressing the button.

**Comment by Nepitwin** [comment]
@Mavnus04 

Nice to hear. Yeah the xpath search could cause some search time. Then the gui node tree is depending on tree node from all gui elements by the xpath. The best way is always to use the full path to avoid long searchs times.

But sometimes you have to use the search if xpath are changed moderatly by thirdparty guis.
