### ISSUE TITLE
Feature: Return coordinates of bounding rectangle of an element

### ISSUE THREAD

**Issue by nizwiz** [GDATASoftwareAG/robotframework-flaui#63]
As far as I could gather from the keyword documentation, there is no possiblity, yet, to determine the bounding rectangle of an element using FlaUILibrary. However, this would be very useful to be able to combine UIA elemet location with other UI automation technologies like image recognition / OCR (e.g. using [robotframework-sikulixlibrary](https://github.com/adrian-evo/robotframework-sikulixlibrary)). There are applications where you can go only so far via UIA alone (e.g. Delphi based GUI applications).
 So the scenario would:
* Locate an element via XPath using FlaUILibrary and gets its bounding rectangle coordinates
* Search within this rectangle via image recognition / OCR using other libraries

**Comment by Nepitwin** [comment]
Sounds for an nice improvement which keyword do you think would be intresting.

I think about keywords like:

- Get Top Left Position -> Returns [X, Y, Width, Height]
- Get Top Right Position -> Returns [X,Y, -Width, Height]
- Get Bottom Left Position -> Returns [X, Y, Width, -Height]
- Get Bottom Right Position -> Returns [X, Y, -Width, -Height]
- Get Center Position -> Returns [X, Y]
- Get Width -> [Returns Width]
- Get Height -> [Returns Height]

Do you have any recommendations?

I think it should be easily to implement if FlaUI gets the property usage from this positions.

**Comment by nizwiz** [comment]
I think this one should actually suffice:

Get Bounding Rectangle -> Returns [X, Y, Width, Height] as either a 4-tuple or dict / object (your choice).

Everything else can be extracted/calculated from the result using inline python expressions.

**Comment by Nepitwin** [comment]
Okay fine then we will made it simple by Get Bounding Rectangle

@noubar Can you implement this new feature? :)

**Comment by nizwiz** [comment]
Thank you very much!
