### ISSUE TITLE
No such file or directory: 'Readme.md'

### ISSUE THREAD

**Issue by naagf5** [GDATASoftwareAG/robotframework-flaui#66]
i am installing like
  pip install -r requirements.txt 
and my requirement file is having   robotframework-flaui==1.6.4

Collecting robotframework-flaui==1.6.4
  Downloading robotframework-flaui-1.6.4.tar.gz (253 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: /jenkins/venv/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-iuaysvg_/robotframework-flaui/setup.py'"'"'; __file__='"'"'/tmp/pip-install-iuaysvg_/robotframework-flaui/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-l40mc5hd
       cwd: /tmp/pip-install-iuaysvg_/robotframework-flaui/
  Complete output (12 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-iuaysvg_/robotframework-flaui/setup.py", line 30, in <module>
      with open("Readme.md", "r") as fh:
  FileNotFoundError: [Errno 2] No such file or directory: 'Readme.md'

**Comment by naagf5** [comment]
i figured out its failing on linux environment and which is not supported by this library. But can the error message be more clear.

We can close this issue if you feel

**Comment by Nepitwin** [comment]
Yes robotframework-flaui is only for windows usage because of UIA interfaces from microsoft windows.

I will close this issue.
