### ISSUE TITLE
Is there any way to get the background colour of a button in FlaUI?

### ISSUE THREAD

**Issue by Muthuvenaktesh** [GDATASoftwareAG/robotframework-flaui#72]
Is there any way to get the background colour of a button in FlaUI ?

I need to check whether the Button background colour is getting changed when I click on it.

**Comment by Nepitwin** [comment]
@Muthuvenaktesh 

Can you show an example from the property currently only name, text properties can be reached from flaui.

Keywords like a Get Value From Property "XPATH" "Property" does not exists in the current scope. I have to recheck if flaui already has the ability to access an specific property from a element.

**Comment by noubar** [comment]
Under FLAUI itself a text has an attribute called BackgroundColor 
There was also an issue opened at FLAUI's side:
https://github.com/FlaUI/FlaUI/issues/176

I will assume a button has text and its text should have the attribute background color.

**Comment by Muthuvenaktesh** [comment]
@Nepitwin 

I have a button which background colour will change based on the action, for example red--> orange and orange --> blue.

Need to get the background colour of this button based on XPATH, for validating the actions/click is worked or not.

![Button_Color](https://user-images.githubusercontent.com/43955483/188083292-4fc45708-11e1-403b-a857-2ad622018273.JPG)
![Button-Color](https://user-images.githubusercontent.com/43955483/188083296-09e8d069-de55-41ad-a820-acc0822919a9.JPG)

**Comment by noubar** [comment]
@Muthuvenaktesh 
Currently we do not support the button as automation element.
So it is also not possible to reach the properties of it even when the flaui itself supports it.

**Comment by Muthuvenaktesh** [comment]
Hi @Nepitwin 

Need a help !!! I wanted to try the same with class names.

I have class names in my exe, I can see it in the developer tools. But in the FlaUI inspect tool class name is showing as not supported.  Please refer the below screen shot. Please le me know what could be the issue.

![image](https://user-images.githubusercontent.com/43955483/211304735-4365bc1b-f276-4461-a2a3-981cb6f845c7.png)

**Comment by Nepitwin** [comment]
I started to implemented property access to element values. New additional property keywords will be implemented to access on specific properties.

**Comment by JanR-W** [comment]
> Value attribute can be accessed by 'Get Text From Textbox' keyword which you can use as workaround currently! But we thank you for your comment such suggestions are important for newer feature supports.

Thank you for that information - I can confirm that using 'Get Text From Textbox' is also working for the element I was experimenting with!

> I started to implemented property access to element values. New additional property keywords will be implemented to access on specific properties.

Also thank you very much - that sounds like a promising enhancement to the library!

**Comment by Nepitwin** [comment]
New supported keyword properties will be:

  - Get Background Color  "xpath"
  - Get Foreground Color  "xpath"
  - Get Font Size  "xpath"
  - Get Font Name  "xpath"
  - Get Font Weight  "xpath"
  - Get Culture  "xpath" <-- Will only work for UIA3 an UIA2 bug exists see https://github.com/FlaUI/FlaUI/issues/554
  - Is Hidden  "xpath"
  - Is Visible  "xpath"
  - Get Window Visual State  "xpath"  <-- "Normal, Maximized, Minimized"

I know they are a lot of properties but for the start it should be enough if a batch is missing an implementation can be easily done by property module now.

This keywords will be released for Robotframework-FlaUI 1.X and 2.X
