### ISSUE TITLE
Flaui 1.6.6r requires pythonnet>=2.5.2

### ISSUE THREAD

**Issue by Marciland** [GDATASoftwareAG/robotframework-flaui#76]
Pythonnet released a new 3.0.0 which results in errors. Can you update release 1.6.6 to require exactly pythonnet 2.5.2 please?

**Comment by Nepitwin** [comment]
Version 1.6.6 can't be used because it's pinned by this version. You have to upgrade to version 2.0.0 which is already uploaded by PyPi. Version 1.X is old 2.5.2 Python.Net usage and new major version 2.0.0 is Python.Net 3.0.

**Comment by Marciland** [comment]
Edit Release does not work?

**Comment by Nepitwin** [comment]
You can not redeploy any pypi packages from python and this is not intended by a clean release management. 1.6.6 only supports and is tested by Python.Net 2.5.2.

This major changes from library usages should be guarantee an consistent behavior usage by this library and automated tests and would break up any changes if i do that. So a major upgrade from 1.6.6 to 2.0.0 is needed and required to use the latest robotframework-flaui. 

1.6.6 is an very old release version you should migrate to 1.7.3 or to 2.0.0. 

Here is a fully list from all changes between 1.6.6 to 2.0.0 

https://github.com/GDATASoftwareAG/robotframework-flaui/compare/1.6.6...2.0.0
