### ISSUE TITLE
Please provide a keyword: wait_until_element_is_enabled

### ISSUE THREAD

**Issue by JimRevolutionist** [GDATASoftwareAG/robotframework-flaui#94]
Dear author
    I know that you have provide a keyword: wait_until_element_is_visible, but it's not available for element like button to wait until it is enabled then to click it.
   So that. please provide a keyword to wait until element is enabled. Please deal with it in your spare time.

Thanks

**Comment by JimRevolutionist** [comment]
pr link:
https://github.com/GDATASoftwareAG/robotframework-flaui/pull/95

**Comment by noubar** [comment]
The Feature is implemented and PR is waiting.

**Comment by noubar** [comment]
Completed
