### ISSUE TITLE
Should Be Visible passes when element is covered by another window.

### ISSUE THREAD

**Issue by Mavnus04** [GDATASoftwareAG/robotframework-flaui#96]
When one window is covering the element on another window, and I try to click on that element, it will give me `FlaUiError: Element position could not be found because it is hidden.`  Even though `FlaUILibrary.Element Should Be Visible` returns True/Pass

```
Click on GUI element
    [Documentation]
    ...     Keyword to mouse click on a GUI element with a xPath
    ...     
    ...     Args:
    ...     - element: Dictionary obj with a key-value pair of 'xPath': 'path/to/element'
    [Arguments]  ${element}
    Log Many  ${element}
    GUI Element Should Exist And Be Visible  ${element}
    FlaUILibrary.Click  ${element}[xPath]

GUI Element Should Exist And Be Visible 
    [Arguments]     ${element}
    Log Many  ${element}
    FlaUILibrary.Element Should Exist  ${element}[xPath]
    FlaUILibrary.Element Should Be Visible  ${element}[xPath]
```

Modified Post by @Mavnus04 in https://github.com/GDATASoftwareAG/robotframework-flaui/issues/92#issuecomment-1472642351_

**Comment by noubar** [comment]
Use:
    FlaUILibrary.Element Should Exist  ${element}[xPath]
    FlaUILibrary.Element Should Be Visible  ${element}[xPath]
    FlaUILibrary.Focus  ${element}[xPath]

**Comment by noubar** [comment]
focus keyword brings it to front so it can be clickable and not hidden under other window.

**Comment by Mavnus04** [comment]
Then what is the point of checking for Visible then?  If the element is hidden under another window, would it be considered not visible?

**Comment by noubar** [comment]
I thought after checking is visible maybe something poping in front.
If it is not the case then i cannot tell what is happennig unless you provide more info or log.

**Comment by Mavnus04** [comment]
Nothing is popping in front.  It just happens to be that exists and visible both return true, even if another window is covering that element. 

Yes, using `Focus` brings the element to the top/front layer.  But I feel that visible should return false if is not clickable. 
Or if just going to use `Focus`, why check for visible at all?

**Comment by noubar** [comment]
We give an access to the IsOffscreen property from https://github.com/FlaUI/FlaUI/blob/master/src/FlaUI.Core/AutomationElements/AutomationElement.cs#L145
and they use in turn the Windows isofscreen property https://learn.microsoft.com/en-us/dotnet/api/system.windows.automation.automationelement.automationelementinformation.isoffscreen

As you can see in the middle of windows automation link:
"The value of the property is not affected by occlusion by other windows, or by whether the element is visible on a specific monitor."

**Comment by Mavnus04** [comment]
Another suggestion, rename "Visible" to "Offscreen" to avoid confusion.  Or update the documentation to explain the actual behavior this functionality is performing.

**Comment by Nepitwin** [comment]
We will change in future this keyword by naming and release this as 2.1.0 version. 

Which include these changes to adjust by developers to increase understanding about keywords.

**Comment by Nepitwin** [comment]
Latest changes are:

### Added
- [#96](https://github.com/GDATASoftwareAG/robotframework-flaui/issues/96) New Keywords
  - Is Element Offscreen
  - Wait Until Element Is Offscreen

### Changed
- [#96](https://github.com/GDATASoftwareAG/robotframework-flaui/issues/96) Multiple Keywords renamed because of misleading keyword understanding
  - 'Element Should Be Visible' to 'Is Element Offscreen'
  - 'Wait Until Element Is Visible' to 'Wait Until Element Exist'
  - 'Wait Until Element Is Hidden' to 'Wait Until Element Does Not Exist'
