### ISSUE TITLE
Unable to update version 2 or higher

### ISSUE THREAD

**Issue by Mavnus04** [GDATASoftwareAG/robotframework-flaui#97]
When attempting to install to version 2.0 or higher, I get install errors. 

```
C:\>python --version
Python 3.7.9

C:\>python -m pip --version
pip 23.0.1 from C:\Program Files\Python37\lib\site-packages\pip (python 3.7)

C:\>python -m pip show setuptools
Name: setuptools
Version: 67.6.0

C:\>python -m pip show robotframework-flaui
Name: robotframework-flaui
Version: 1.7.3

C:\>python -m pip install --upgrade robotframework-flaui
Requirement already satisfied: robotframework-flaui in c:\program files\python37\lib\site-packages (1.7.3)
Collecting robotframework-flaui
  Using cached robotframework-flaui-2.0.6.tar.gz (263 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [13 lines of output]
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\USERNAME\AppData\Local\Temp\pip-install-uhn4xndc\robotframework-flaui_d619f16cba6145b9982505404dca6e78\setup.py", line 34, in <module>
          with open("requirements.txt", "r") as f:
      FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
      ---------------------Branch Informations---------------------
      Release: False
      APPVEYOR_REPO_TAG: false
      APPVEYOR_REPO_TAG_NAME: 0
      APPVEYOR_BUILD_VERSION: 0
      APPVEYOR_BUILD_NUMBER: 0
      -------------------------------------------------------------
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by noubar** [comment]
In error it says:
File "C:\Users\USERNAME\AppData\Local\Temp\pip-install-uhn4xndc\robotframework-flaui_d619f16cba6145b9982505404dca6e78\setup.py", line 34, in <module>

Which is trying to reach some chached data (localy). It usually says  Downloading robotframework_flaui-2.0.6......
This can be a curropted cache data. I would suggest you to uninstall robotframework-flaui and reinstall it.

**Comment by noubar** [comment]
or try to upgrade your python version to >= 3.8

**Comment by Mavnus04** [comment]
No cache option didn't work, same error as before:

```
>python -m pip install --upgrade --no-cache robotframework-flaui
Requirement already satisfied: robotframework-flaui in c:\program files\python37\lib\site-packages (1.7.3)
Collecting robotframework-flaui
  Downloading robotframework-flaui-2.0.6.tar.gz (263 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 263.2/263.2 kB 2.7 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [13 lines of output]
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\USERNAME\AppData\Local\Temp\pip-install-cysq_a5w\robotframework-flaui_e39727dcac964800b3073297254749aa\setup.py", line 34, in <module>
          with open("requirements.txt", "r") as f:
      FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
      ---------------------Branch Informations---------------------
      Release: False
      APPVEYOR_REPO_TAG: false
      APPVEYOR_REPO_TAG_NAME: 0
      APPVEYOR_BUILD_VERSION: 0
      APPVEYOR_BUILD_NUMBER: 0
      -------------------------------------------------------------
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

Un-installed the old one, and attempted a fresh clean install, same error:

```
>python -m pip install --no-cache robotframework-flaui
Collecting robotframework-flaui
  Downloading robotframework-flaui-2.0.6.tar.gz (263 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 263.2/263.2 kB 2.0 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [13 lines of output]
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\MATTHE~1.MUM\AppData\Local\Temp\pip-install-s74johw0\robotframework-flaui_601a01b24e524c0992bd1da3b7610883\setup.py", line 34, in <module>
          with open("requirements.txt", "r") as f:
      FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
      ---------------------Branch Informations---------------------
      Release: False
      APPVEYOR_REPO_TAG: false
      APPVEYOR_REPO_TAG_NAME: 0
      APPVEYOR_BUILD_VERSION: 0
      APPVEYOR_BUILD_NUMBER: 0
      -------------------------------------------------------------
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

Our system and setup is based on 3.7.  Not looking at upgrading anytime soon.  Is there something else you can do?

**Comment by Mavnus04** [comment]
Using this, I was able to download and see the contents of what was being grabbed
`C:\test>python -m pip download --no-cache -d C:\test\download --no-clean robotframework-flaui`

And there is no `requirements.txt` file in the downloaded contents:
<img width="208" alt="image" src="https://user-images.githubusercontent.com/24551506/227999966-81cb5b76-067b-4f10-995d-d347380270a6.png">

**Comment by noubar** [comment]
I have tested:
Python >=3.8 has no problem 
Python 3.7 has the problem

@Nepitwin do we not support 3.7 python for newer verstions of flauilibrary?

**Comment by Nepitwin** [comment]
Ah okay i see the issue. We only build for python 3.8, 3.9 and 3.10 wheel files. So afterwards requirements.txt is missing by source code which is downloaded and try to build this environment and fails. I will include these to next furter release 2.0.8 to include this files to guarantee this version to build.

**Comment by Nepitwin** [comment]
After upgrade i could successfully build this library by python 3.7

> pip install --upgrade robotframework-flaui --no-cache
Collecting robotframework-flaui
  Downloading robotframework-flaui-2.0.8.tar.gz (263 kB)
     |████████████████████████████████| 263 kB 3.3 MB/s
Collecting robotframework>=3.2.2
  Downloading robotframework-6.0.2-py3-none-any.whl (658 kB)
     |████████████████████████████████| 658 kB 6.4 MB/s
Collecting typing-extensions>=3.10.0.0
  Downloading typing_extensions-4.5.0-py3-none-any.whl (27 kB)
Collecting robotframework-pythonlibcore>=3.0.0
  Downloading robotframework_pythonlibcore-4.1.2-py2.py3-none-any.whl (10 kB)
Collecting pythonnet==3.0.1
  Downloading pythonnet-3.0.1-py3-none-any.whl (284 kB)
     |████████████████████████████████| 284 kB 3.3 MB/s
Collecting clr-loader<0.3.0,>=0.2.2
  Downloading clr_loader-0.2.5-py3-none-any.whl (51 kB)
     |████████████████████████████████| 51 kB ...
Collecting cffi>=1.13
  Downloading cffi-1.15.1-cp37-cp37m-win_amd64.whl (179 kB)
     |████████████████████████████████| 179 kB 6.8 MB/s
Collecting pycparser
  Downloading pycparser-2.21-py2.py3-none-any.whl (118 kB)
     |████████████████████████████████| 118 kB 6.8 MB/s
Using legacy setup.py install for robotframework-flaui, since package 'wheel' is not installed.
Installing collected packages: robotframework, typing-extensions, robotframework-pythonlibcore, pycparser, cffi, clr-loader, pythonnet, robotframework-flaui
    Running setup.py install for robotframework-flaui ... done
Successfully installed cffi-1.15.1 clr-loader-0.2.5 pycparser-2.21 pythonnet-3.0.1 robotframework-6.0.2 robotframework-flaui-0rc0 robotframework-pythonlibcore-4.1.2 typing-extensions-4.5.0

Don't forget to ignore cached version by parameter

 pip install --upgrade robotframework-flaui --no-cache

**Comment by Nepitwin** [comment]
You can asweel ignore message about version --> robotframework-flaui-0rc0

This is already fixxed for further releases to display correct installation version. Old setup.py does not use version from sources.

**Comment by Nepitwin** [comment]
Version 2.0.9 works now expected with Python 3.11 or Python 3.7 installation. @Mavnus04 

Thanks for you feedback about the issue.
