### ISSUE TITLE
Wait Until Element Is Hidden (wrong)

### ISSUE THREAD

**Issue by noubar** [GDATASoftwareAG/robotframework-flaui#99]
The keyword "Wait Until Element Is Hidden" does not wait until the element is offscreen but waits untill element does not exist anymore.

suggestion:
Rename the keyword to "Wait Until Element Is Gone".
Reimplement the "Wait Until Element Is Hidden" right way.

**Comment by Nepitwin** [comment]
If the keyword is wrong by usage simple fix it. ;)

An keyword Wait Until Element Is Gone is not a nice naming asweel.

**Comment by JimRevolutionist** [comment]
@noubar @Nepitwin 
Because of the not available function to check.
Should use "_element_should_not_be_visible" on this line
![image](https://user-images.githubusercontent.com/126214844/231669607-9e829f23-b45b-4648-b7ac-9cc2e7495c92.png)

**Comment by Nepitwin** [comment]
@JimRevolutionist 

Your totally right we will adjust this line of code on correct behavior.

**Comment by Nepitwin** [comment]
Upcoming changes in this method is:

- If element does not exists element is hidden
- If element is offscreen element is hidden

**Comment by Nepitwin** [comment]
@noubar  @JimRevolutionist 

After some investigation. IsOffscreen is a wrong usage here.
IsOffscreen returns asweel False if window is minimized.

Wait Until Element Is Visible and Hidden means more i think related to the implementation that it should Wait Until A Element Exists (Visible) or Not Existing (Hidden).

I rethink to change these type of keyword to

Wait Until Element Exist and Wait Until Element Not Exist to clarify this type of keywords.

Visible and Hidden does not mean that this elements are displaying on screen. But this type of Keyword for

Wait Until Element Is Visible or Hidden would be a better approach to use WindowVisualState which shows Minimized (Hidden) and Maximized (Visible)

**Comment by JimRevolutionist** [comment]
@Nepitwin 

Window.WindowVisualState property still cannot completely indicate an element is visible or hidden.
Because its value has 3 cases: Normal (0) | Maximized (1) | Minimized (2)
When your window is covered by another window, the property value is still one of 3 cases ahead, not like Covered or Hidden.

**Comment by Nepitwin** [comment]
### Updated
- [#96](https://github.com/GDATASoftwareAG/robotframework-flaui/issues/96) Keyword 'Is Element Offscreen' and 'Wait Until Element Is Offscreen' replaced deleted keywords

### Removed
- [#96](https://github.com/GDATASoftwareAG/robotframework-flaui/issues/96) Keywords 'Element Should Be Visible', 'Element Should Not Be Visible', 'Wait Until Element Is Visible'
  - Misleading implementation from this keyword which does not verify if Element was visible or not
  - Offscreen has been checked

**Comment by Nepitwin** [comment]
Changes are done in keywords by latest robotframework-flaui 2.1.0 version issue will be closed.
